name: Send Job Alerts

on:
  schedule:
    - cron: "45 8 * * *"
  workflow_dispatch:

jobs:
  send-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scheduler task
        env:
          X_API_Key: ${{secrets.X_API_Key}}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          gmail_password: ${{ secrets.gmail_password }}
        run: |
          python src/scheduler.py
